// <auto-generated />
namespace SchedulingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initalSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201603291350344_initalSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
